### ISSUE TITLE
Compatibility with eclipse milo

### ISSUE THREAD

**Issue by lln-ijinus** [kevinherron/uanodeset-parser#1]
Hi,

I would like to know how to use the parser and if it is compatible with the eclipse milo ?
In fact I would need the DI schema (https://opcfoundation.org/UA/schemas/DI/1.1/Opc.Ua.Di.NodeSet2.xml) in my milo server...

Thanks

**Comment by kevinherron** [comment]
The intention is to be compatible, yes. I have another project that uses this and makes loading the companion namespaces easy but it's not quite ready yet. You shouldn't have to use this project directly. I'll try to mention loading external models when I put together the simple roadmap for Milo.

**Comment by Pro** [comment]
Hi @kevinherron,
is there any update on the integration of the nodeset-parser for Milo, or is there already an example somewhere?

I would also need to load the DI into Milo...

**Comment by kevinherron** [comment]
Huh, didn't realize this was still public.

It's not quite ready yet. No documentation, API stability, or examples. Right now this thing changes as I need it to change for the code generator (also private right now) that uses it.

**Comment by kevinherron** [comment]
FWIW, once the code generator stabilizes, this can stabilize, at which point I will publish various companion spec models such as DI as add-on libraries. I want these libraries to include code-generated instances of all the ObjectTypes, VariableTypes, and Methods from whatever UANodeSet it's modeling.
